---
# Calamares settings for NeoArch
instances:
  - id:       neoarch
    module:   contextualprocess
    config:   contextualprocess.conf

  - id:       neoarch-bootloader
    module:   bootloader
    config:   bootloader.conf

  - id:       neoarch-netinstall
    module:   netinstall
    config:   netinstall.conf

modules-search: [ local ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
    - netinstall
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - luksbootkeyfile
    - luksopenswaphookcfg
    - dracut
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - grubcfg
    - bootloader
    - users
    - contextualprocess
    - packages
    - postcfg
    - umount

branding: neoarch

welcome:
  showSupportUrl: false
  showKnownIssuesUrl: false
  showDonateUrl: false
  showFeedbackUrl: false
  showReleaseNotesUrl: false
