---
# Bootloader configuration for NeoArch
efiBootLoaderId: "neoarch"
kernelLine: "quiet splash loglevel=3 udev.log_priority=3 nowatchdog nvme_load=YES"
kernelParams:
  - quiet
  - splash
  - loglevel=3
  - udev.log_priority=3
  - nowatchdog
  - nvme_load=YES
fallbackKernelLine: "loglevel=3 nowatchdog nomodeset"
timeout: "5"
