---
# Display manager configuration
displaymanagers:
  - sddm

basicSetup: false

sysconfigSetup: true

defaultDesktopEnvironment:
  file: /usr/share/xsessions/plasma.desktop
  executable: startplasma-x11

autologin:
  - username: ""
    session: plasma
