---
# Systemd services for NeoArch
services:
  - name: NetworkManager
    action: enable
    mandatory: true

  - name: sddm
    action: enable
    mandatory: true

  - name: bluetooth
    action: enable
    mandatory: false

  - name: irqbalance
    action: enable
    mandatory: false

  - name: preload
    action: enable
    mandatory: false

  - name: haveged
    action: enable
    mandatory: false

  - name: ananicy
    action: enable
    mandatory: false

  - name: fstrim.timer
    action: enable
    mandatory: true

  - name: paccache.timer
    action: enable
    mandatory: true

  - name: snapper-timeline.timer
    action: enable
    mandatory: false

  - name: snapper-cleanup.timer
    action: enable
    mandatory: false

  - name: earlyoom
    action: enable
    mandatory: false

  - name: auto-cpufreq
    action: enable
    mandatory: false

  - name: tuned
    action: enable
    mandatory: false

  - name: systemd-timesyncd
    action: enable
    mandatory: true
