#
# /etc/mkinitcpio.conf - optimized for neoarch
#

MODULES=(btrfs nvme ahci xhci-hcd nls_utf8)
BINARIES=(btrfs mkfs.btrfs fsck.btrfs)
FILES=()
HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont block encrypt lvm2 filesystems fsck)
COMPRESSION="zstd"
COMPRESSION_OPTIONS=("-T0" "--ultra" "-22")
MODULES_DECOMPRESS="yes"
